wanditem:
  name: "Home registerer"
  lore:
    - "With this item you can register"
    - "Your home warp."
  cost: 10
  canbuy: true
blankcouponitem:
  name: "Blank warp ticket"
  lore:
    - "Blank ticket ready to link"
    - "with home sign"
  cost: 1
  canbuy: true

# {warp} line is important to show where coupon lead to
couponitem:
  name: "Warp ticket"
  lore:
    - "Ticket linked to:"
    - "{warp}"

messages:
  wrong_stack_amount: "Set valid stack value"
  buying_disable: "Homedepot buy is disabled."
  not_enough_for_item: "You don't have enough money to buy {item}."
  you_payed: "You pay {cost} for {amount} {item}"
  create_permission: "&cYou do not have the required permissions to create home signs!"
  no_warp_name: "&cNo warp name set!\nPlease specify the warp name on the second line."
  warp_created: "&aWarp successfully placed."
  warp_name_taken: "&cA warp target with the same name already exists!"
  warp_destroyed: "&aWarp destroyed."
  target_sign_created: "&aTarget sign for warp successfully placed."
  destroy_permission: "&cYou do not have the required permissions to destroy warp signs!"
  invalid_item: "&cYou must use {use-item} for this warp!"
  not_enough_item: "&cYou need {use-cost} {use-item} for this warp!"
  warp_not_found: "&cSpecified warp does not exist!"
  use_permission: "&cYou do not have the required permissions to use the warp sign!"
  teleport: "&eTeleporting to {warp-name} in {time} seconds..."
  teleport-success: "&aSuccessfully teleported to {warp-name}."
  teleport-error: "&aAn error occured {warp-name}."
  teleport-cancelled: "&cTeleport cancelled."
  notify-cost: "&aYou have been charged {cost} currency for the teleportation."
  not_permission: "&cYou do not have permission!"