#Option canbuy is to set if items can be buy by commands, and give opportunity to create other ways to obtain items by player.
wanditem:
  name: "Home registerer"
  lore:
    - "With this item you can register"
    - "Your home warp."
  cost: 10
  canbuy: true
blankcouponitem:
  name: "Blank warp ticket"
  lore:
    - "Blank ticket ready to link"
    - "with home sign"
  cost: 1
  canbuy: true

# {warp} is important to show where coupon lead to
couponitem:
  name: "Warp ticket"
  lore:
    - "Ticket linked to:"
    - "{warp}"

teleportcooldown: 1

messages:
  wrong_stack_amount: "Wrong amount value"
  buying_disable: "Homedepot buy is disabled."
  not_enough_for_item: "You don't have enough money to buy {item}."
  you_payed: "You pay {cost} for {amount} {item}"
  create_permission: "&cYou do not have the required permissions to create home signs!"
  no_warp_name: "&cNo warp name set!\nPlease specify the warp name."
  warp_created: "&aWarp successfully placed."
  warp_name_taken: "&cA warp target with the same name already exists!"
  warp_destroyed: "&aWarp destroyed."
  warp_on_sign_not_exist: "&cWarp on this sign is not registered!"
  target_sign_created: "&aHome successfully registered."
  destroy_permission: "&cYou do not have the required permissions to destroy warp signs!"
  warp_not_found: "&cSpecified warp does not exist!"
  teleport: "&eTeleporting to {warp-name} in {time} seconds..."
  teleport-success: "&aSuccessfully teleported to {warp-name}."
  teleport-error: "&aAn error occured, when teleporting to: {warp-name}."
  teleport-cancelled: "&cTeleport cancelled."