wanditem:
  name: "Rejestrator domu"
  lore:
    - "Z tym zarejestrujesz dom."
  cost: 10
  canbuy: true
blankcouponitem:
  name: "Czysty kupon powrotu"
  lore:
    - "Kupon który musisz najpierw"
    - "połączyć z domem"
  cost: 1
  canbuy: true
couponitem:
  name: "Kupon powrotu"
  lore:
    - "Kupon połączony z miejscem:"

# Custom messages
messages:
  wrong_stack_amount: "Podaj prawidłowy rozmiar stosu"
  buying_disable: "Kupowanie przedmiotów jest wyłączone"
  not_enough_for_item: "Nie stać cię na {item}."
  you_payed: "You pay {cost} for {amount} {item}"
  create_permission: "&cYou do not have the required permissions to create home signs!"
  no_warp_name: "&cNo warp name set!\nPlease specify the warp name on the second line."
  warp_created: "&aWarp successfully placed."
  warp_name_taken: "&cA warp target with the same name already exists!"
  warp_destroyed: "&aWarp destroyed."
  target_sign_created: "&aTarget sign for warp successfully placed."
  destroy_permission: "&cYou do not have the required permissions to destroy warp signs!"
  invalid_item: "&cYou must use {use-item} for this warp!"
  not_enough_item: "&cYou need {use-cost} {use-item} for this warp!"
  warp_not_found: "&cSpecified warp does not exist!"
  use_permission: "&cYou do not have the required permissions to use the warp sign!"
  teleport: "&eTeleporting to {warp-name} in {time} seconds..."
  teleport-success: "&aSuccessfully teleported to {warp-name}."
  teleport-error: "&aAn error occured {warp-name}."
  teleport-cancelled: "&cTeleport cancelled."
  notify-cost: "&aYou have been charged {cost} currency for the teleportation."
  not_permission: "&cYou do not have permission!"