#Option canbuy is to set if items can be buy by commands, and give opportunity to create other ways to obtain items by player.
#cost value doesn't work without properly configured vault.
canbuy: true
registerer:
  name: "Home registerer"
  lore:
    - "With this item you can"
    - "Register your home."
  material: "STICK"
  cost: 10
blankticket:
  name: "Blank ticket"
  lore:
    - "Blank ticket ready to link"
    - "with home sign"
  material: "PAPER"
  cost: 1

# {home} is important to show where coupon lead to, but it's not necessary
ticket:
  name: "Home ticket"
  lore:
    - "Ticket linked to:"
    - "{home}"
  material: "PAPER"

teleportcooldown: 1

messages:
  wrong_stack_amount: "Wrong stack amount value"
  buying_disabled: "Homedepot buy command is disabled."
  not_enough_for_item: "You don't have enough money to buy {item}."
  you_paid: "You paid {cost} for {amount} {item}"
  create_permission: "You do not have the required permissions to create home signs!"
  no_home_name: "No home name set!\nPlease specify the home name."
  home_created: "Home successfully registered."
  home_name_taken: "A home with the same name already exists!"
  home_destroyed: "Home destroyed."
  home_on_sign_not_exist: "Home on this sign is not registered!"
  home_sign_created: "Home successfully registered."
  destroy_permission: "You do not have the required permissions to destroy home signs!"
  home_not_found: "Specified home does not exist!"
  teleport: "Teleporting to {home} in {time} seconds..."
  teleport-success: "Successfully teleported to {home}."
  teleport-error: "An error occured, when teleporting to: {home}."
  teleport-cancelled: "Teleport cancelled."
  item_cost: "{item} cost {cost}"
  economy_false: "Economy plugin is not enabled on server."
  item_received: "{player} received {amount} {item}."