wanditem:
  name: "Pałka domostwa"
  lore:
    l1: "Pałka do rejestracji domu."
blankcouponitem:
  name: "Czysty kupon powrotu"
  lore:
    l1: "Kupon który musisz najpierw"
    l2: "połączyć z domem"
couponitem:
  name: "Kupon powrotu"
  lore:
    l1: "Kupon połączony z domem:"
    

# Custom messages
messages:
  create_permission: "&cYou do not have the required permissions to create warp signs!"
  no_warp_name: "&cNo warp name set!\nPlease specify the warp name on the second line."
  warp_created: "&aWarp sign successfully placed."
  warp_name_taken: "&cA warp target with the same name already exists!"
  warp_destroyed: "&aWarp destroyed."
  target_sign_created: "&aTarget sign for warp successfully placed."
  destroy_permission: "&cYou do not have the required permissions to destroy warp signs!"
  invalid_item: "&cYou must use {use-item} for this warp!"
  not_enough_item: "&cYou need {use-cost} {use-item} for this warp!"
  warp_not_found: "&cSpecified warp does not exist!"
  use_permission: "&cYou do not have the required permissions to use the warp sign!"
  teleport: "&eTeleporting to {warp-name} in {time} seconds..."
  teleport-success: "&aSuccessfully teleported to {warp-name}."
  teleport-error: "&aAn error occured {warp-name}."
  teleport-cancelled: "&cTeleport cancelled."
  notify-cost: "&aYou have been charged {cost} currency for the teleportation."
  not_permission: "&cYou do not have permission!"