name: 'Blank'
version: '1.0.0'
main: com.hemostaza.blank.BlankPlugin
api-version: '1.21.3'
commands:
  blank:
    description: give items or set warp
    usage: /blank setwarp/delwarp ogólnie to chuj jak nie wiesz o co chodzi to pewnie nie powinienes meic uprawnień hujku