name: 'HomeRegistry'
version: '1.0.0'
main: com.hemostaza.homeregister.MainPlugin
api-version: '1.21'
softdepend:
  - Vault
commands:
  homeregistry:
    description: "Main commands for HomeRegistry"
    usage: "/homeregistry <subcommands>"
    aliases: ["hr"]
    permission: homeregistry.commands
    permission-message: 'You do not have permission to run this command'
  homeregistrybuy:
    description: "Buy items necessary for registering house"
    usage: "/homeregistrybuy <registerer/coupon/howmuch>"
    aliases: ["hrbuy","hrb"]
permissions:
  homeregistry.*:
    children:
      - homeregistry.create
      - homeregistry.use
      - homeregistry.commands
      - homeregistry.remove
  homeregistry.create:
    description: "Allows you to create home signs"
    default: true
  homeregistry.use:
    description: "Allow uses of home signs"
    default: true
  homeregistry.commands:
    description: "Allows you to use op commands"
    default: op
  homeregistry.remove:
    description: "Allows you to remove everyone home sign"
    default: op
