name: 'HomeRegistry'
version: '1.0.0'
main: com.hemostaza.homeregister.MainPlugin
api-version: '1.21.3'
softdepend:
  - Vault
commands:
  homedepot:
    description: "Homedepot commands"
    usage: "/homedepot <subcommand>"
    aliases: ["hd"]
    permission: homedepot.commands
  homedepotbuy:
    description: "Buy items necessary for registering house"
    usage: "/homedepotbuy <registerer/coupon/howmuch>"
    aliases: ["hdbuy","hdb"]
permissions:
  homedepot.*:
    children:
      - homedepot.create
      - homedepot.use
      - homedepot.destroy
      - homedepot.commands
      - homedepot.remove
  homedepot.create:
    description: "Allows you to create home signs"
    default: true
  homedepot.use:
    description: "Allow uses of home signs"
    default: true
  homedepot.destroy:
    description: "Allows you to destroy your sign"
    default: true
  homedepot.commands:
    description: "Allows you to use op commands"
    default: op
  homedepot.remove:
    description: "Allows you to remove everyone home sign"
    default: op
