name: 'Blank'
version: '1.0.0'
main: com.hemostaza.blank.BlankPlugin
api-version: '1.21.3'
commands:
  blank:
    description: pesnis
    usage: fakju
  transferexp:
    description: transfer exp to the holding bottles
    usage: chuj?